spring.application.name=rentACar

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/rentACar}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security Configurations
# Base64 sifrelenmis, sistemi taniyip imzalayacak cok guclu min 256-bit gizli anahtar
# JWT Secret Key (Minimum 256 bits for HS256)
jwt.secret.key=${JWT_SECRET}
# Tokenin Omru: 1 Gun (86400000 milisaniye)
jwt.expiration.time=86400000

# System Default Super Admin Credentials
system.admin.email=${ADMIN_EMAIL:admin@rentacar.com}
system.admin.password=${ADMIN_PASSWORD:12345}

# Cloudinary Image Upload Configurations
# (Bu degerleri https://cloudinary.com adresinden ucretsiz hesap olusturup, Dashboard'daki bilgileri buraya yapistir)
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Multipart File Upload Size Limit (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Resilience4j Rate Limiting Configurations (Saniyede max 20 istek - Genel API)
resilience4j.ratelimiter.instances.api-rate-limiter.limit-for-period=20
resilience4j.ratelimiter.instances.api-rate-limiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.api-rate-limiter.timeout-duration=0s

# Sadece Auth (Giriş / Kayıt) için özel Rate Limiter (Dakikada max 6 istek)
resilience4j.ratelimiter.instances.auth-rate-limiter.limit-for-period=6
resilience4j.ratelimiter.instances.auth-rate-limiter.limit-refresh-period=60s
resilience4j.ratelimiter.instances.auth-rate-limiter.timeout-duration=0s

# Spring Boot Actuator (Sağlık ve İzleme) Ayarları
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Redis Global Cache Sunucusu Ayarları
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.repositories.enabled=false
