spring.application.name=rentACar

spring.datasource.url=jdbc:postgresql://localhost:5432/rentACar
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security Configurations
# Base64 sifrelenmis, sistemi taniyip imzalayacak cok guclu min 256-bit gizli anahtar
jwt.secret.key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Tokenin Omru: 1 Gun (86400000 milisaniye)
jwt.expiration.time=86400000

# System Default Super Admin Credentials
system.admin.email=admin@rentacar.com
system.admin.password=12345

# Cloudinary Image Upload Configurations
# (Bu degerleri https://cloudinary.com adresinden ucretsiz hesap olusturup, Dashboard'daki bilgileri buraya yapistir)
cloudinary.cloud_name=dyiupcy0v
cloudinary.api_key=533617747987792
cloudinary.api_secret=49zwIKFldLmBTQqwiFFz2zbm_4I

# Multipart File Upload Size Limit (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Resilience4j Rate Limiting Configurations (Saniyede max 20 istek - Genel API)
resilience4j.ratelimiter.instances.api-rate-limiter.limit-for-period=20
resilience4j.ratelimiter.instances.api-rate-limiter.limit-refresh-period=1s
resilience4j.ratelimiter.instances.api-rate-limiter.timeout-duration=0s
